# Generated by Django 6.0.2 on 2026-03-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('idCategorieDepense', models.AutoField(primary_key=True, serialize=False)),
                ('NomCategorie', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépense',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('idFamille', models.AutoField(primary_key=True, serialize=False)),
                ('NomFamille', models.CharField(max_length=100)),
                ('NombreMembres', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('idModePaiement', models.AutoField(primary_key=True, serialize=False)),
                ('NomMode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
            },
        ),
        migrations.CreateModel(
            name='TypeRevenu',
            fields=[
                ('idTypeRevenu', models.AutoField(primary_key=True, serialize=False)),
                ('NomType', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Type de revenu',
                'verbose_name_plural': 'Types de revenu',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('idMembre', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Role', models.CharField(choices=[('parent', 'Parent'), ('enfant', 'Enfant'), ('autre', 'Autre')], default='enfant', max_length=20)),
                ('idFamille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='gestionbudgetfamille10.famille')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('idDepense', models.AutoField(primary_key=True, serialize=False)),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('idCategorieDepense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbudgetfamille10.categoriedepense')),
                ('idMembre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='gestionbudgetfamille10.membre')),
                ('idModePaiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbudgetfamille10.modepaiement')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('idRevenu', models.AutoField(primary_key=True, serialize=False)),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('idMembre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenus', to='gestionbudgetfamille10.membre')),
                ('idTypeRevenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbudgetfamille10.typerevenu')),
            ],
            options={
                'verbose_name': 'Revenu',
                'verbose_name_plural': 'Revenus',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('idBudget', models.AutoField(primary_key=True, serialize=False)),
                ('Mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')])),
                ('Annee', models.IntegerField()),
                ('MontantPrevu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFamille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='gestionbudgetfamille10.famille')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('Mois', 'Annee', 'idFamille')},
            },
        ),
    ]
